#This is a basic Deployment file that will get exposed by a service(Nodeport).

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paascoe-deployment
spec:
  selector:
    matchLabels:
      app: paascoe
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: 
    metadata:
      labels:
        app: paascoe
    spec:
      containers:
      - name: paascoe
        image: sauravsrivastav/web:v1
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: paascoe-service
spec:
  selector:
    app: paascoe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30111 #30k-32767
  type: NodePort