apiVersion: v1
kind: Secret
metadata:
  name:  mssql-secret
data:
   db-connection-string-secret: ZGItY29ubmVjdGlvbi1zdHJpbmc6IFNlcnZlcj1tc3NxbC1zZXJ2aWNlO0RhdGFiYXNlPUVtcGxveWVlc0RCO1VzZXI9U0E7UGFzc3dvcmQ9U2F1cmF2QDEyMzs=
type: Opaque

#BASE64_ENCODED_VALUE echo -n 'admin' | base64
# echo -n 'db-connection-string: Server=mssql-service;Database=EmployeesDB;User=SA;Password=Saurav@123;' | base64
# db-connection-string: Server=mssql-service;Database=EmployeesDB;User=SA;Password=Saurav@123;

