#It will live inside the cluster

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-persistent-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce #accissible from one single pod.
  hostPath: # path to store our volume.
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim #abstraction of PV
metadata:
  name: mssql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

#After this go to basic-mssql1.yaml file to use this to provide voulme created by PV and PVC.